version: "3"

services:
  ##Server##
  server:
    build: ./server
    expose:
      - "4000"
    environment:
      API_HOST: "http://localhost:4000/"
      APP_SERVER_PORT: "4000"
    ports:
      - 4000:4000
    volumes:
      - ./server/src:/srv/app/fr-shohin-admin-server/src
    command: node index

  ##Client##

  client:
    build: ./client
    expose:
      - 5000
    environment:
      PORT: "5000"
    ports:
      - 5000:5000
    volumes:
      - ./client/src:/srv/app/fr-shohin-admin-client/src
      - ./client/public:/srv/app/fr-shohin-admin-client/public
    links:
      - server
    command: npm run start
